package com.example.individ1.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;
@Getter
@Setter
public class Fund {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FUND.ID
     *
     * @mbg.generated Sat Apr 23 18:43:27 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FUND.NAME
     *
     * @mbg.generated Sat Apr 23 18:43:27 EEST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FUND.ID
     *
     * @return the value of PUBLIC.FUND.ID
     *
     * @mbg.generated Sat Apr 23 18:43:27 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FUND.ID
     *
     * @param id the value for PUBLIC.FUND.ID
     *
     * @mbg.generated Sat Apr 23 18:43:27 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FUND.NAME
     *
     * @return the value of PUBLIC.FUND.NAME
     *
     * @mbg.generated Sat Apr 23 18:43:27 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FUND.NAME
     *
     * @param name the value for PUBLIC.FUND.NAME
     *
     * @mbg.generated Sat Apr 23 18:43:27 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    public List<Stock> stocks;
    public List<Manager> managers;
}
