package com.example.individ1.mybatis.model;

public class FundsStocks {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FUNDS_STOCKS.STOCK_ID
     *
     * @mbg.generated Mon Apr 25 23:43:32 EEST 2022
     */
    private Integer stockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FUNDS_STOCKS.FUND_ID
     *
     * @mbg.generated Mon Apr 25 23:43:32 EEST 2022
     */
    private Integer fundId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FUNDS_STOCKS.STOCK_ID
     *
     * @return the value of PUBLIC.FUNDS_STOCKS.STOCK_ID
     *
     * @mbg.generated Mon Apr 25 23:43:32 EEST 2022
     */
    public Integer getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FUNDS_STOCKS.STOCK_ID
     *
     * @param stockId the value for PUBLIC.FUNDS_STOCKS.STOCK_ID
     *
     * @mbg.generated Mon Apr 25 23:43:32 EEST 2022
     */
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FUNDS_STOCKS.FUND_ID
     *
     * @return the value of PUBLIC.FUNDS_STOCKS.FUND_ID
     *
     * @mbg.generated Mon Apr 25 23:43:32 EEST 2022
     */
    public Integer getFundId() {
        return fundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FUNDS_STOCKS.FUND_ID
     *
     * @param fundId the value for PUBLIC.FUNDS_STOCKS.FUND_ID
     *
     * @mbg.generated Mon Apr 25 23:43:32 EEST 2022
     */
    public void setFundId(Integer fundId) {
        this.fundId = fundId;
    }
}