package com.example.individ1.mybatis.model;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MANAGER.ID
     *
     * @mbg.generated Sat Apr 23 14:45:43 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MANAGER.NAME
     *
     * @mbg.generated Sat Apr 23 14:45:43 EEST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MANAGER.ID
     *
     * @return the value of PUBLIC.MANAGER.ID
     *
     * @mbg.generated Sat Apr 23 14:45:43 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MANAGER.ID
     *
     * @param id the value for PUBLIC.MANAGER.ID
     *
     * @mbg.generated Sat Apr 23 14:45:43 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MANAGER.NAME
     *
     * @return the value of PUBLIC.MANAGER.NAME
     *
     * @mbg.generated Sat Apr 23 14:45:43 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MANAGER.NAME
     *
     * @param name the value for PUBLIC.MANAGER.NAME
     *
     * @mbg.generated Sat Apr 23 14:45:43 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    private Fund fund;
    private Long fundId;
}