package com.example.individ1.mybatis.dao;

import com.example.individ1.mybatis.model.FundsStocks;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface FundsStocksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FUNDS_STOCKS
     *
     * @mbg.generated Mon Apr 25 23:43:32 EEST 2022
     */
    int deleteByPrimaryKey(@Param("stockId") Integer stockId, @Param("fundId") Integer fundId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FUNDS_STOCKS
     *
     * @mbg.generated Mon Apr 25 23:43:32 EEST 2022
     */
    int insert(FundsStocks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FUNDS_STOCKS
     *
     * @mbg.generated Mon Apr 25 23:43:32 EEST 2022
     */
    List<FundsStocks> selectAll();
}