package com.example.individ1.mybatis.dao;

import com.example.individ1.mybatis.model.Manager;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface ManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANAGER
     *
     * @mbg.generated Sat Apr 23 14:45:43 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANAGER
     *
     * @mbg.generated Sat Apr 23 14:45:43 EEST 2022
     */
    int insert(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANAGER
     *
     * @mbg.generated Sat Apr 23 14:45:43 EEST 2022
     */
    Manager selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANAGER
     *
     * @mbg.generated Sat Apr 23 14:45:43 EEST 2022
     */
    List<Manager> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANAGER
     *
     * @mbg.generated Sat Apr 23 14:45:43 EEST 2022
     */
    int updateByPrimaryKey(Manager record);
}