package com.example.individ1.mybatis.dao;

import com.example.individ1.mybatis.model.Stock;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface StockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STOCK
     *
     * @mbg.generated Sat Apr 23 14:40:33 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STOCK
     *
     * @mbg.generated Sat Apr 23 14:40:33 EEST 2022
     */
    int insert(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STOCK
     *
     * @mbg.generated Sat Apr 23 14:40:33 EEST 2022
     */
    Stock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STOCK
     *
     * @mbg.generated Sat Apr 23 14:40:33 EEST 2022
     */
    List<Stock> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STOCK
     *
     * @mbg.generated Sat Apr 23 14:40:33 EEST 2022
     */
    int updateByPrimaryKey(Stock record);
}